#!/bin/bash
# Install all packages from linux_inventory (excluding: i3, i3status, i3lock, dunst, feh, arandr, autorandr, kitty, alacritty, brightnessctl, rofi, picom)
set -e

sudo apt update
sudo apt install -y \
    accountsservice \
    acl \
    acpi \
    adduser \
    adwaita-icon-theme \
    alsa-base \
    alsa-topology-conf \
    alsa-ucm-conf \
    alsa-utils \
    amd64-microcode \
    anacron \
    apache2 \
    apache2-bin \
    apache2-data \
    apache2-utils \
    apg \
    apparmor \
    apport \
    apport-core-dump-handler \
    apport-gtk \
    apport-symptoms \
    appstream \
    apt \
    apt-config-icons \
    apt-config-icons-hidpi \
    apt-transport-https \
    apt-utils \
    aptdaemon \
    aptdaemon-data \
    aria2 \
    aspell \
    aspell-en \
    at-spi2-common \
    at-spi2-core \
    avahi-daemon \
    baobab \
    base-files \
    base-passwd \
    bash \
    bash-completion \
    bat \
    bc \
    bibutils \
    bind9-dnsutils \
    bind9-host \
    binutils \
    binutils-common \
    binutils-x86-64-linux-gnu \
    bison \
    blt \
    blueman \
    bluez \
    bluez-cups \
    bluez-obexd \
    bolt \
    bpfcc-tools \
    bpftool \
    bpftrace \
    brasero-common \
    brightness-udev \
    brltty \
    bsdextrautils \
    bsdutils \
    btop \
    bubblewrap \
    build-essential \
    busybox-initramfs \
    busybox-static \
    byacc \
    bzip2 \
    bzip2-doc \
    ca-certificates \
    ca-certificates-java \
    cdrdao \
    cloud-guest-utils \
    cloud-init \
    cloud-init-base \
    cmake \
    cmake-data \
    colord \
    colord-data \
    command-not-found \
    console-setup \
    console-setup-linux \
    containerd.io \
    coreutils \
    cpdb-backend-cups \
    cpio \
    cpp \
    cpp-x86-64-linux-gnu \
    cpu-checker \
    cracklib-runtime \
    crash \
    cron \
    cron-daemon-common \
    cups \
    cups-browsed \
    cups-bsd \
    cups-client \
    cups-common \
    cups-core-drivers \
    cups-daemon \
    cups-filters \
    cups-filters-core-drivers \
    cups-ipp-utils \
    cups-pk-helper \
    cups-ppdc \
    cups-server-common \
    curl \
    dash \
    dbconfig-common \
    dbconfig-mysql \
    dbus \
    dbus-bin \
    dbus-daemon \
    dbus-session-bus-common \
    dbus-system-bus-common \
    dbus-user-session \
    dc \
    dconf-cli \
    dconf-gsettings-backend \
    dconf-service \
    debconf \
    debconf-i18n \
    debianutils \
    default-jre \
    default-jre-headless \
    desktop-file-utils \
    dex \
    dhcpcd-base \
    dictionaries-common \
    diffutils \
    dirmngr \
    discord \
    distro-info \
    distro-info-data \
    dmidecode \
    dmsetup \
    dmz-cursor-theme \
    dns-root-data \
    dnsmasq-base \
    docbook-xml \
    docker-buildx-plugin \
    docker-ce \
    docker-ce-cli \
    docker-ce-rootless-extras \
    docker-compose-plugin \
    docx2txt \
    dosfstools \
    dpkg \
    dpkg-dev \
    dracut-install \
    e2fsprogs \
    e2fsprogs-l10n \
    eatmydata \
    ed \
    efibootmgr \
    eject \
    emacsen-common \
    enchant-2 \
    eog \
    eslint \
    espeak-ng-data \
    ethtool \
    evolution-data-server \
    evolution-data-server-common \
    exfatprogs \
    exo-utils \
    eza \
    fakeroot \
    fdisk \
    ffmpeg \
    file \
    findutils \
    firebird-utils \
    firebird4.0-common \
    firebird4.0-common-doc \
    firebird4.0-server-core \
    firebird4.0-utils \
    firefox \
    firmware-sof-signed \
    flex \
    fontconfig \
    fontconfig-config \
    foomatic-db-compressed-ppds \
    fprintd \
    friendly-recovery \
    ftp \
    fuse3 \
    fwupd \
    fwupd-signed \
    fzf \
    g++ \
    g++-x86-64-linux-gnu \
    galera-4 \
    gamemode \
    gamemode-daemon \
    gawk \
    gcc \
    gcc-x86-64-linux-gnu \
    gcr \
    gcr4 \
    gdb \
    gdisk \
    gdm3 \
    gedit \
    gedit-common \
    geoclue-2.0 \
    geocode-glib-common \
    gettext-base \
    ghostscript \
    git \
    git-man \
    gjs \
    glib-networking \
    glib-networking-common \
    glib-networking-services \
    gnome-accessibility-themes \
    gnome-bluetooth-3-common \
    gnome-calculator \
    gnome-characters \
    gnome-clocks \
    gnome-control-center \
    gnome-control-center-data \
    gnome-control-center-faces \
    gnome-desktop3-data \
    gnome-disk-utility \
    gnome-font-viewer \
    gnome-initial-setup \
    gnome-keyring \
    gnome-keyring-pkcs11 \
    gnome-logs \
    gnome-menus \
    gnome-online-accounts \
    gnome-power-manager \
    gnome-remote-desktop \
    gnome-session-bin \
    gnome-session-canberra \
    gnome-session-common \
    gnome-settings-daemon \
    gnome-settings-daemon-common \
    gnome-shell \
    gnome-shell-common \
    gnome-shell-extension-appindicator \
    gnome-shell-extension-desktop-icons-ng \
    gnome-shell-extension-ubuntu-dock \
    gnome-shell-extension-ubuntu-tiling-assistant \
    gnome-startup-applications \
    gnome-system-monitor \
    gnome-terminal \
    gnome-terminal-data \
    gnome-text-editor \
    gnome-themes-extra \
    gnome-themes-extra-data \
    gnome-user-docs \
    gnupg \
    gnupg-l10n \
    gnupg-utils \
    golang-1.24-go \
    golang-1.24-src \
    golang-any \
    golang-go \
    golang-src \
    gpg \
    gpg-agent \
    gpg-wks-client \
    gpgconf \
    gpgsm \
    gpgv \
    grep \
    groff-base \
    grub-common \
    grub-efi-amd64 \
    grub-efi-amd64-bin \
    grub-efi-amd64-signed \
    grub-efi-amd64-unsigned \
    grub-pc \
    grub2-common \
    gsettings-desktop-schemas \
    gsettings-ubuntu-schemas \
    gstreamer1.0-alsa \
    gstreamer1.0-gl \
    gstreamer1.0-gtk3 \
    gstreamer1.0-packagekit \
    gstreamer1.0-pipewire \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-base-apps \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-tools \
    gstreamer1.0-x \
    gthumb \
    gthumb-data \
    gtk-update-icon-cache \
    gtk2-engines-murrine \
    gtk2-engines-pixbuf \
    gvfs \
    gvfs-backends \
    gvfs-common \
    gvfs-daemons \
    gvfs-fuse \
    gvfs-libs \
    gyp \
    gzip \
    handlebars \
    hdparm \
    heif-gdk-pixbuf \
    heif-thumbnailer \
    hicolor-icon-theme \
    hostname \
    hplip \
    hplip-data \
    htop \
    hugo \
    hunspell-en-us \
    hwdata \
    ibus \
    ibus-data \
    ibus-gtk \
    ibus-gtk3 \
    ibus-gtk4 \
    ibus-table \
    ibus-table-cangjie-big \
    ibus-table-cangjie3 \
    ibus-table-cangjie5 \
    ibverbs-providers \
    icc-profiles-free \
    idle \
    idle-python3.13 \
    ieee-data \
    iio-sensor-proxy \
    im-config \
    imagemagick-7-common \
    inetutils-telnet \
    info \
    init \
    init-system-helpers \
    initramfs-tools \
    initramfs-tools-bin \
    initramfs-tools-core \
    inputattach \
    install-info \
    intel-microcode \
    ipp-usb \
    iproute2 \
    iptables \
    iputils-ping \
    iputils-tracepath \
    ipxe-qemu \
    ipxe-qemu-256k-compat-efi-roms \
    iso-codes \
    iucode-tool \
    iw \
    java-common \
    java-wrappers \
    javascript-common \
    jing \
    jq \
    kbd \
    kdump-tools \
    kexec-tools \
    keyboard-configuration \
    keyboxd \
    keyd \
    kitty-doc \
    kitty-shell-integration \
    kitty-terminfo \
    klibc-utils \
    kmod \
    krb5-locales \
    language-pack-en \
    language-pack-en-base \
    language-pack-gnome-en \
    language-pack-gnome-en-base \
    language-selector-common \
    language-selector-gnome \
    laptop-detect \
    ldap-utils \
    less \
    locales \
    login \
    login.defs \
    logrotate \
    logsave \
    lsb-release \
    lshw \
    lsof \
    lto-disabled-list \
    luit \
    m17n-db \
    m4 \
    make \
    makedumpfile \
    man-db \
    manpages \
    manpages-dev \
    mariadb-client \
    mariadb-client-core \
    mariadb-common \
    mariadb-plugin-provider-bzip2 \
    mariadb-plugin-provider-lz4 \
    mariadb-plugin-provider-lzma \
    mariadb-plugin-provider-lzo \
    mariadb-plugin-provider-snappy \
    mariadb-server \
    mariadb-server-core \
    mawk \
    media-types \
    memtest86+ \
    mesa-common-dev \
    mesa-libgallium \
    mesa-vdpau-drivers \
    mesa-vulkan-drivers \
    mobile-broadband-provider-info \
    modemmanager \
    mokutil \
    mongodb-compass \
    mongodb-database-tools \
    mongodb-mongosh \
    mongodb-org \
    mongodb-org-database \
    mongodb-org-database-tools-extra \
    mongodb-org-mongos \
    mongodb-org-server \
    mongodb-org-shell \
    mongodb-org-tools \
    mount \
    mousetweaks \
    mpv \
    mscompress \
    msr-tools \
    mtr-tiny \
    mutter-common \
    mutter-common-bin \
    mysql-common \
    mysql-server \
    nano \
    nasm \
    nautilus \
    nautilus-data \
    nautilus-extension-gnome-terminal \
    nautilus-sendto \
    ncurses-base \
    ncurses-bin \
    net-tools \
    netbase \
    netcat-openbsd \
    netplan-generator \
    netplan.io \
    network-manager \
    network-manager-config-connectivity-ubuntu \
    network-manager-openvpn \
    network-manager-openvpn-gnome \
    network-manager-pptp \
    network-manager-pptp-gnome \
    networkd-dispatcher \
    nftables \
    nm-connection-editor \
    nodejs \
    nodejs-doc \
    npm \
    ntfs-3g \
    numactl \
    nvidia-settings \
    obs-plugins \
    obs-studio \
    ocl-icd-libopencl1 \
    openjdk-21-jre \
    openjdk-21-jre-headless \
    openprinting-ppds \
    openssh-client \
    openssl \
    openssl-provider-legacy \
    openvpn \
    orca \
    os-prober \
    ovmf \
    p11-kit \
    p11-kit-modules \
    packagekit \
    packagekit-tools \
    papers \
    papers-common \
    parted \
    passwd \
    patch \
    pavucontrol \
    pci.ids \
    pciutils \
    pcmciautils \
    perl \
    perl-base \
    perl-modules-5.40 \
    perl-openssl-defaults \
    php \
    php-bcmath \
    php-bz2 \
    php-common \
    php-composer-ca-bundle \
    php-curl \
    php-fig-http-message-util \
    php-gd \
    php-getallheaders \
    php-google-recaptcha \
    php-mariadb-mysql-kbs \
    php-mbstring \
    php-mcrypt \
    php-mysql \
    php-nikic-fast-route \
    php-phpmyadmin-motranslator \
    php-phpmyadmin-shapefile \
    php-phpmyadmin-sql-parser \
    php-psr-cache \
    php-psr-container \
    php-psr-http-factory \
    php-psr-http-message \
    php-psr-log \
    php-slim-psr7 \
    php-symfony-cache \
    php-symfony-cache-contracts \
    php-symfony-config \
    php-symfony-dependency-injection \
    php-symfony-deprecation-contracts \
    php-symfony-expression-language \
    php-symfony-filesystem \
    php-symfony-service-contracts \
    php-symfony-var-exporter \
    php-tcpdf \
    php-twig \
    php-twig-i18n-extension \
    php-webmozart-assert \
    php-xml \
    php-zip \
    phpmyadmin \
    pigz \
    pinentry-curses \
    pinentry-gnome3 \
    pipewire \
    pipewire-bin \
    pipewire-pulse \
    pkexec \
    pkg-config \
    pkgconf \
    pkgconf-bin \
    playerctl \
    plymouth \
    plymouth-label \
    plymouth-theme-spinner \
    plymouth-theme-ubuntu-text \
    pnp.ids \
    pocketsphinx-en-us \
    policykit-desktop-privileges \
    polkitd \
    polybar \
    poppler-data \
    poppler-utils \
    postgresql \
    postgresql-17 \
    postgresql-17-pgvector \
    postgresql-client-17 \
    postgresql-client-common \
    postgresql-common \
    postgresql-common-dev \
    power-profiles-daemon \
    powermgmt-base \
    ppp \
    pptp-linux \
    printer-driver-brlaser \
    printer-driver-c2esp \
    printer-driver-foo2zjs \
    printer-driver-foo2zjs-common \
    printer-driver-hpcups \
    printer-driver-m2300w \
    printer-driver-min12xxw \
    printer-driver-pnm2ppa \
    printer-driver-postscript-hp \
    printer-driver-ptouch \
    printer-driver-pxljr \
    printer-driver-sag-gdi \
    printer-driver-splix \
    procps \
    psmisc \
    publicsuffix \
    pulseaudio \
    pulseaudio-utils \
    pv \
    py3status \
    python-apt-common \
    python-babel-localedata \
    python3 \
    python3-apport \
    python3-apt \
    python3-aptdaemon \
    python3-aptdaemon.gtk3widgets \
    python3-attr \
    python3-autocommand \
    python3-babel \
    python3-bcrypt \
    python3-blinker \
    python3-bpfcc \
    python3-brlapi \
    python3-cairo \
    python3-certifi \
    python3-cffi-backend \
    python3-chardet \
    python3-click \
    python3-commandnotfound \
    python3-configobj \
    python3-cryptography \
    python3-cups \
    python3-cupshelpers \
    python3-dateutil \
    python3-dbus \
    python3-debconf \
    python3-debian \
    python3-defer \
    python3-dev \
    python3-distro \
    python3-distro-info \
    python3-distupgrade \
    python3-doc \
    python3-examples \
    python3-full \
    python3-gdbm \
    python3-gi \
    python3-gi-cairo \
    python3-httplib2 \
    python3-ibus-1.0 \
    python3-idna \
    python3-inflect \
    python3-jaraco.context \
    python3-jaraco.functools \
    python3-jinja2 \
    python3-json-pointer \
    python3-jsonpatch \
    python3-jsonschema \
    python3-jsonschema-specifications \
    python3-jwt \
    python3-launchpadlib \
    python3-lazr.restfulclient \
    python3-lazr.uri \
    python3-libevdev \
    python3-louis \
    python3-markdown-it \
    python3-markupsafe \
    python3-mdurl \
    python3-minimal \
    python3-more-itertools \
    python3-mutagen \
    python3-nautilus \
    python3-netaddr \
    python3-netifaces \
    python3-netplan \
    python3-oauthlib \
    python3-olefile \
    python3-packaging \
    python3-passlib \
    python3-pexpect \
    python3-pil \
    python3-pip \
    python3-pip-whl \
    python3-pkg-resources \
    python3-problem-report \
    python3-ptyprocess \
    python3-pycryptodome \
    python3-pygments \
    python3-pyparsing \
    python3-pyudev \
    python3-referencing \
    python3-requests \
    python3-rich \
    python3-rpds-py \
    python3-serial \
    python3-setuptools-whl \
    python3-software-properties \
    python3-speechd \
    python3-sss \
    python3-systemd \
    python3-tk \
    python3-typeguard \
    python3-typing-extensions \
    python3-uno \
    python3-update-manager \
    python3-urllib3 \
    python3-venv \
    python3-wadllib \
    python3-websockets \
    python3-wheel \
    python3-xdg \
    python3-xkit \
    python3-yaml \
    qemu-block-extra \
    qemu-system-common \
    qemu-system-data \
    qemu-system-gui \
    qemu-system-modules-opengl \
    qemu-system-modules-spice \
    qemu-system-x86 \
    qemu-utils \
    qt5-gtk-platformtheme \
    qt6-gtk-platformtheme \
    qt6-image-formats-plugins \
    qt6-qpa-plugins \
    qt6-svg-plugins \
    qt6-translations-l10n \
    qt6-wayland \
    qttranslations5-l10n \
    qtwayland5 \
    readline-common \
    redis-server \
    redis-tools \
    redshift \
    rfkill \
    rpcsvc-proto \
    rsync \
    rsyslog \
    rtkit \
    rygel \
    samba-libs \
    sane-airscan \
    sane-utils \
    sbsigntool \
    scrot \
    seabios \
    seahorse \
    secureboot-db \
    sed \
    sensible-utils \
    session-migration \
    sgml-base \
    sgml-data \
    shared-mime-info \
    shim-signed \
    slirp4netns \
    snapd \
    socat \
    software-properties-common \
    software-properties-gtk \
    sound-icons \
    sound-theme-freedesktop \
    speech-dispatcher \
    speech-dispatcher-audio-plugins \
    speech-dispatcher-espeak-ng \
    speedtest-cli \
    spice-vdagent \
    sqlite3 \
    sqlitebrowser \
    squashfs-tools \
    ssl-cert \
    sssd \
    sssd-ad \
    sssd-ad-common \
    sssd-common \
    sssd-ipa \
    sssd-krb5 \
    sssd-krb5-common \
    sssd-ldap \
    sssd-proxy \
    strace \
    suckless-tools \
    sudo \
    switcheroo-control \
    sysprof \
    sysstat \
    system-config-printer-common \
    system-config-printer-udev \
    systemd \
    systemd-cryptsetup \
    systemd-hwe-hwdb \
    systemd-oomd \
    systemd-resolved \
    systemd-sysv \
    systemd-timesyncd \
    sysvinit-utils \
    tar \
    tcl \
    tcl8.6 \
    tcpdump \
    tecla \
    telnet \
    terser \
    thermald \
    thunar \
    thunar-data \
    thunar-volman \
    tilix \
    tilix-common \
    time \
    timgm6mb-soundfont \
    tinysparql \
    tk8.6-blt2.5 \
    tnftp \
    tpm-udev \
    trace-cmd \
    tracker-extract \
    tree \
    tumbler \
    tumbler-common \
    tzdata \
    ubuntu-advantage-desktop-daemon \
    ubuntu-desktop-minimal \
    ubuntu-docs \
    ubuntu-drivers-common \
    ubuntu-kernel-accessories \
    ubuntu-keyring \
    ubuntu-minimal \
    ubuntu-pro-client \
    ubuntu-pro-client-l10n \
    ubuntu-release-upgrader-core \
    ubuntu-release-upgrader-gtk \
    ubuntu-report \
    ubuntu-session \
    ubuntu-session-xsession \
    ubuntu-settings \
    ubuntu-standard \
    ubuntu-wallpapers \
    ubuntu-wallpapers-plucky \
    ucf \
    udev \
    udisks2 \
    ufw \
    unattended-upgrades \
    uno-libs-private \
    unzip \
    update-inetd \
    update-manager \
    update-manager-core \
    update-notifier \
    update-notifier-common \
    upower \
    ure \
    ure-java \
    usb-modeswitch \
    usb-modeswitch-data \
    usb.ids \
    usbmuxd \
    usbutils \
    util-linux \
    uuid-dev \
    uuid-runtime \
    vdpau-driver-all \
    vim \
    vim-common \
    vim-runtime \
    vim-tiny \
    virtiofsd \
    vlc \
    vlc-bin \
    vlc-data \
    vlc-l10n \
    vlc-plugin-access-extra \
    vlc-plugin-base \
    vlc-plugin-notify \
    vlc-plugin-qt \
    vlc-plugin-samba \
    vlc-plugin-skins2 \
    vlc-plugin-video-output \
    vlc-plugin-video-splitter \
    vlc-plugin-visualization \
    wamerican \
    webp-pixbuf-loader \
    webpack \
    wget \
    whiptail \
    whoopsie \
    whoopsie-preferences \
    wireless-regdb \
    wireplumber \
    wpasupplicant \
    wsdd \
    x11-apps \
    x11-common \
    x11-session-utils \
    x11-utils \
    x11-xkb-utils \
    x11-xserver-utils \
    x11proto-dev \
    xauth \
    xbitmaps \
    xbrlapi \
    xclip \
    xcursor-themes \
    xcvt \
    xdg-dbus-proxy \
    xdg-desktop-portal \
    xdg-desktop-portal-gnome \
    xdg-desktop-portal-gtk \
    xdg-terminal-exec \
    xdg-user-dirs \
    xdg-user-dirs-gtk \
    xdg-utils \
    xfconf \
    xfonts-base \
    xfonts-encodings \
    xfonts-scalable \
    xfonts-utils \
    xinit \
    xinput \
    xkb-data \
    xml-core \
    xorg \
    xorg-dev \
    xorg-docs-core \
    xorg-sgml-doctools \
    xserver-common \
    xserver-xephyr \
    xserver-xorg \
    xserver-xorg-core \
    xserver-xorg-dev \
    xserver-xorg-input-all \
    xserver-xorg-input-libinput \
    xserver-xorg-input-wacom \
    xserver-xorg-legacy \
    xserver-xorg-video-all \
    xserver-xorg-video-amdgpu \
    xserver-xorg-video-ati \
    xserver-xorg-video-fbdev \
    xserver-xorg-video-intel \
    xserver-xorg-video-nouveau \
    xserver-xorg-video-qxl \
    xserver-xorg-video-radeon \
    xserver-xorg-video-vesa \
    xserver-xorg-video-vmware \
    xss-lock \
    xtrans-dev \
    xwayland \
    xxd \
    xz-utils \
    yaru-theme-gnome-shell \
    yaru-theme-gtk \
    yaru-theme-icon \
    yaru-theme-sound \
    yelp \
    yelp-xsl \
    yt-dlp \
    yudit-common \
    zenity \
    zenity-common \
    zip \
    zlib1g \
    zlib1g-dev \
    zstd

echo "All packages installed successfully."
