# Generated by Django 5.2.8 on 2025-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_sample_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='username',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_mobile',
            field=models.CharField(default='000000', max_length=15),
            preserve_default=False,
        ),
    ]
