# Generated by Django 5.2.8 on 2025-11-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sample',
            new_name='UserData',
        ),
    ]
