CREATE TABLE emp(emp_id SERIAL PRIMARY KEY,fname VARCHAR(50) NOT NULL,
    lname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    dept VARCHAR(50),
    salary DECIMAL(10,2) NOT NULL DEFAULT 15000.00,
    hire_date DATE NOT NULL );